"""
Kho tuc ngu, ca dao Viet Nam - nguon: tong hop tuc ngu dan gian Viet Nam.
Moi ngay bot chon ngau nhien 1 cau (seed theo ngay, nen 1 ngay chi ra 1 cau co dinh,
nhung khong theo thu tu de doan truoc duoc).
"""
import random
from datetime import date

PROVERBS = [
    "Ao có bờ sông có bến",
    "Ăn quả nhớ kẻ trồng cây",
    "Ăn khoai nhớ kẻ cho dây mà trồng",
    "Ăn cây nào rào cây nấy",
    "Ăn cháo đá bát",
    "Ăn chắc mặc bền",
    "Ăn cho sạch bạch cho nông",
    "Ăn cỗ đi trước, lội nước theo sau",
    "Ăn cơm nhà vác tù và hàng tổng",
    "Ăn cơm trước kẻng",
    "Ăn đầu sóng, nói đầu gió",
    "Ăn kĩ no lâu, cày sâu tốt lúa",
    "Ăn không lo của kho cũng hết",
    "Ăn không ngồi rồi",
    "Ăn ngay nói thẳng",
    "Ăn theo thuở, ở theo thời",
    "Ăn trông nồi ngồi trông hướng",
    "Ăn vóc học hay",
    "Ăn cây nào, rào cây nấy",
    "Ăn chưa no, lo chưa tới",
    "Ăn cơm không rau như nhà giàu chết không nhạc",
    "Ăn cơm có canh như tu hành có bạn",
    "Ăn cơm mới, nói chuyện cũ",
    "Ăn dầm, nằm dề",
    "Ăn đi giỗ trước, lội nước theo sau",
    "Ân trả nghĩa đền",
    "Ân đoạn nghĩa tuyệt",
    "Bàn tay ta làm nên tất cả",
    "Có sức người sỏi đá cũng thành cơm.",
    "Bé đi câu, lớn đi hầu, già đi hỏi nợ",
    "Bé người con nhà bác, lớn xác con nhà người",
    "Bé người to con mắt",
    "Bé người đòi chơi trèo",
    "Bè thì bè lon, sào thì sào sậy",
    "Bè ai người ấy chống",
    "Buôn có bạn, bán có phường",
    "Bụt chùa nhà không thiêng",
    "Bạn bè con chấy cắn đôi",
    "Bạn bè là nghĩa tương tri",
    "Bầu ơi thương lấy bí cùng , tuy rằng khác giống nhưng chung một giàn",
    "Bán anh em xa, mua láng giềng gần",
    "Có chí thì nên",
    "Cây có cội, nước có nguồn",
    "Cây cao bóng cả",
    "Có công mài sắt, có ngày nên kim.",
    "Có cô thì chợ cũng đông, cô đi lấy chồng thì chợ vẫn vui",
    "Của đi thay người",
    "Cái răng, cái tóc là góc con người.",
    "Cái kim trong bọc cũng có ngày lòi ra",
    "Con trâu là đầu cơ nghiệp",
    "Cái khó ló cái khôn",
    "Cần cù bù thông minh",
    "Có mới nới cũ",
    "Có mới thì nới cũ ra, mới để trong nhà cũ bỏ ngoài sân",
    "Con dại cái mang",
    "Con đàn cháu đống",
    "Con độc cháu đàn",
    "Con hơn cha là nhà có phúc",
    "Con gái cái bòn",
    "Cờ bí dí tốt",
    "Cơm chẳng lành, canh chẳng ngọt",
    "Con có cha như nhà có nóc, con không cha như nòng nọc đứt đuôi",
    "Có cứng mới đứng đầu gió",
    "Chuyện bé xé ra to",
    "Cao chạy xa bay",
    "Chị ngã em nâng",
    "Cầu được ước thấy",
    "Cọp chết để da,người ta chết để tiếng",
    "Chó treo mèo đậy",
    "Dao sắc không gọt được chuôi",
    "Dân giàu nước mạnh.",
    "Dục tốc bất đạt.",
    "Đất lành chim đậu.",
    "Đất lở chim bay",
    "Đi một ngày đàng học một sàng khôn.",
    "Đời cha ăn mặn đời con khát nước.",
    "Đói cho sạch, rách cho thơm.",
    "Đa sầu đa mang.",
    "Đêm tháng năm chưa nằm đã sáng, ngày tháng mười chưa cười đã tối.",
    "Đâm bị thóc, thóc bị gạo.",
    "Đi thưa về gửi.",
    "Đi đến nơi về đến chốn.",
    "Đàn gảy tai trâu.",
    "Đèn nhà ai, nhà nấy rạng.",
    "Đèn nhà bên sáng,gà nhà ta thức",
    "Đầu năm sương muối, cuối năm gió nồm.",
    "Đồng tiền đi liền khúc ruột .",
    "Đất có lề, quê có thói.",
    "Gieo gió gặp bão",
    "Góp gió thành bão",
    "Gieo nhân nào , gặt quả nấy",
    "Giấy rách phải giữ lấy lề",
    "Gần mực thì đen, gần đèn thì sáng",
    "Giận quá mất khôn",
    "Giận cá chém thớt",
    "Gừng càng già càng cay.",
    "Ghét của nào trời trao của nấy",
    "Gạn đục, khơi trong.",
    "Giặc đến nhà đàn bà cũng đánh.",
    "Gan vàng dạ sắt.",
    "Giỏ nhà ai quai nhà nấy",
    "Giống rồng lại đẻ ra rồng",
    "Gà què ăn quẩn cối xay",
    "Giao trứng cho ác.",
    "Gừng cay muối mặn.",
    "Em nghe tiếng hát đâu xa",
    "Còn trẻ hay già mà còn tinh vang.",
    "Êm như ru",
    "Ếch ngồi đáy giếng",
    "Hai đánh một không chột cũng què",
    "Hai hổ phân tranh, nhứt hổ tử thương",
    "Học đi đôi với hành",
    "Học thầy không tày học bạn",
    "Học ăn, học nói, học gói, học mở",
    "Học mười năm biết một ngu si",
    "Chơi mà không học, mất cả tương lai",
    "Học tài thi phận",
    "Hổ chết để da, người ta chết để tiếng",
    "Hi sinh đời bố, củng cố đời con",
    "Học một biết mười",
    "Khôn ăn cái, dại ăn nước.",
    "Khôn đâu tới trẻ, khỏe đâu tới già.",
    "Khôn không qua lẽ, khỏe chẳng qua lời.",
    "Khéo ăn thì no,khéo co thì ấm.",
    "Không làm sao nên.",
    "Không có gì là tuyệt đối.",
    "Kính già, già để tuổi cho.",
    "Kính lão đắc thọ.",
    "Kính trên nhường dưới.",
    "Khi yêu trái ấu cũng tròn, ghét nhau bồ hòn cũng méo.",
    "Không có lửa làm sao có khói.",
    "Không có gì tự nhiên có.",
    "Kẻ cắp gặp bà già.",
    "Khôn chết, dại chết, giả chết không chết.",
    "Khôn nhà, dại chợ.",
    "Khôn ba năm dại một giờ.",
    "Không thầy đố mày làm nên.",
    "Khỉ ho cò gáy.",
    "Kính thầy yêu bạn.",
    "Kết thù làm bạn.",
    "Không nên đề bạn làm thù.",
    "Khỏi vòng cong đuôi.",
    "Kiến tha lâu cũng đầy tổ.",
    "Kiến đen tha trứng lên cao, thế nào cũng có mưa rào rất to.",
    "Khác máu tanh lòng.",
    "Khôn từ trong trứng khôn ra.",
    "Không dưng ai dễ đem phần đến cho.",
    "Khăng khăng quân tử một lời nhất ngôn.",
    "Lá rụng về cội",
    "Lá lành đùm lá rách.",
    "Lên voi xuống chó.",
    "Lời nói chẳng mất tiền mua, lựa lời mà nói coi chừng rụng răng.",
    "Liệu cơm gắp mắm.",
    "Lùi một bước tiến ngàn dặm.",
    "Lửa gần rơm lâu ngày cũng bén.",
    "Lù đù vác cái lu mà chạy.",
    "Lửa thử vàng gian nan thử sức.",
    "Lựa gió xoay chiều.",
    "Lành ít dữ nhiều.",
    "Lắm kẻ yêu hơn nhiều người ghét.",
    "Liệu việc như thần.",
    "Muôn người như một ăn cột mà ra",
    "Một điều nhịn chín điều lành.",
    "Máu chảy ruột mềm.",
    "Máu loãng còn hơn nước lã.",
    "Môi hở, răng lạnh.",
    "Một con ngựa đau, cả tàu bỏ cỏ.",
    "Một con chim én không làm nên mùa xuân.",
    "Một câu nhịn, chín câu lành.",
    "Mất lòng trước, được lòng sau.",
    "Một nụ cười bằng mười thang thuốc bổ.",
    "Mật ngọt chết ruồi.",
    "Mạnh vì gạo, bạo vì tiền.",
    "Miếng ngon nhớ lâu, đòn đau nhớ đời.",
    "Một miếng khi đói bằng một gói khi no.",
    "Muốn ăn thì lăn vào bếp.",
    "Muốn lành nghề, chớ nề học hỏi.",
    "Muốn biết phải hỏi, muốn giỏi phải học.",
    "Một kho vàng không bằng một nang chữ.",
    "Một mặt người bằng mười mặt của.",
    "Ma đưa lối, quỷ dẫn đường.",
    "Mất bò mới lo làm chuồng.",
    "Mau sao thì nắng, vắng sao thì mưa.",
    "Mềm nắn, rắn buông.",
    "Mềm quá thì yếu, cứng quá thì gãy.",
    "Mèo mả gà đồng.",
    "Mèo nhỏ bắt chuột con.",
    "Mèo gặp mỡ.",
    "Mía ngọt đánh cả cụm.",
    "Một người lo bằng kho người làm.",
    "Một thằng tính bằng chín thằng làm.",
    "Một lần ngại tốn, bốn lần chẳng xong.",
    "Một con sâu làm rầu nồi canh",
    "Một chữ cũng là thầy, nửa chữ cũng là thầy.",
    "Một nghề cho chín còn hơn chín nghề.",
    "Mũi dại, lái phải chịu đòn.",
    "Muốn ăn cá cả phải thả câu dài.",
    "Mưu sự tại nhân hành sự tại thiên.",
    "Mẹ hát, con khen hay.",
    "Mẹ cày con cấy.",
    "Một cây làm chẳng nên non, ba cây chụm lại nên hòn núi cao.",
    "Muốn sang thì bắc cầu kiều, muốn con hay chữ thì yêu lấy thầy.",
    "Mua danh ba vạn,bán danh ba đồ.",
    "Mưa tháng ba hoa đất, mưa tháng tư hư đất.",
    "Mèo khen mèo dài đuôi.",
    "Năm nắng mười mưa",
    "Năng làm thì nên.",
    "Nước chảy về nguồn, lá rụng về cội.",
    "Nước lã không huấy nên hồ.",
    "Nước chảy đá mòn.",
    "Nói có sách, mách có chứng.",
    "Nói lời phải giữ lấy lời.",
    "Nồi nào úp vung nấy.",
    "No mất ngon, giận mất khôn.",
    "No bụng đói con mắt.",
    "Năng nhặt chặt bị.",
    "Nó lú có chú nó khôn.",
    "Nói thì hay, bắt tay thì dở.",
    "Nước đổ lá khoai.",
    "Nước chảy, hoa trôi, bèo dạt.",
    "Nói một đàng, làm một nẻo.",
    "Nuôi lợn ăn cơm nằm, nuôi tằm ăn cơm đứng.",
    "Nuôi ong tay áo, nuôi cáo trong nhà.",
    "Nước đổ đầu vịt",
    "Nước lã mà vã nên hồ, tay không mà nổi cơ đồ mới ngoan.",
    "Nói hay hơn hay nói.",
    "Nực cười châu chấu đá xe, tưởng rằng chấu ngã, ai dè xe nghiêng.",
    "Nói trước quên sau.",
    "Nói lời phải giữ lấy lời, Đừng như con bướm đậu rồi lại bay.",
    "Nói người phải nghĩ đến ta, sờ vào sau gáy xem xa hay gần.",
    "Nói người phải nghĩ đến thân, sờ vào sau gáy xem gần hay xa.",
    "Nam thực như hổ, nữ thực như miêu.",
    "Nôm na là cha mánh khóe.",
    "Người sống đống vàng",
    "Nhà sạch thì mát, bát sạch ngon cơm",
    "Nhà giàu đứt tay bằng ăn mày đổ ruột",
    "Nhất thì, nhì thục",
    "Nhất nước, nhì phân, tam cần, tứ giống.",
    "Nhất canh trì, nhị canh viên, tam canh điền.",
    "Nhất quỷ nhì ma, thứ ba học trò",
    "Nhân chi sơ tính bổn thiện",
    "Những người cặp mắt lá răm, đôi mày lá liễu đáng trăm quan tiền.",
    "Nhìn bụng ta, suy ra bụng người.",
    "Nhìn mặt mà bắt hình dong.",
    "Nhất tự vi sư, bán tự vi sư",
    "Nhiễu điều phủ lấy giá gương, Người trong một nước phải thương nhau cùng.",
    "Nhường cơm sẻ áo.",
    "Nhất cận thị, nhị cận giang",
    "Nghèo sinh bệnh, giàu sinh tật.",
    "Người đẹp vì lụa, lúa tốt vì phân.",
    "Ngu dốt mà nhiệt tình thành phá hoại.",
    "Người ta là hoa đất.",
    "Ngưu tầm ngưu, mã tầm mã.",
    "Ngồi mát ăn bát vàng.",
    "Ngọt như mía lùi.",
    "Ngọt mật chết ruồi.",
    "Oán không giải được oán",
    "Oan có đầu, nợ có chủ",
    "Oan oan tương báo , dỉ hận liên miên",
    "Oán thù nên giải không nên kết",
    "Ông thò chân giò, bà thò nậm rượu",
    "Ông nói chó,bà nói mèo",
    "Ở hiền gặp lành, ở ác gặp ác",
    "Ở nhà nghe Đông Hà lúa héo",
    "Ở bầu thì tròn, ở ống thì dài.",
    "Ở xó chuồng heo,hơn là theo phía vợ",
    "Phép nước lệ làng.",
    "Phép vua thua lệ làng.",
    "Phòng bệnh hơn chữa bệnh.",
    "Phúc bất trùng lai, hoạ vô đơn chí.",
    "Quân tử phòng thân; tiểu nhân phòng bị, gậy.",
    "Quân tử nhất ngôn kí xuất, tứ mã nan truy",
    "Quỷ tha, ma bắt",
    "Quả báo nhãn tiền",
    "Quan nhất thời, dân vạn đại",
    "Quýt làm cam chịu",
    "Qua cầu rút ván",
    "Quân tử trả thù mười năm chưa muộn",
    "Rao ngọc bán đá",
    "Ráng mỡ gà có nhà thì chống.",
    "Ráng mỡ gà thì gió , ráng mỡ chó thì mưa.",
    "Rau nào sâu nấy.",
    "Ruộng bề bề chẳng bằng nghề trong tay.",
    "Rừng vàng, biển bạc.",
    "Rừng không hai cọp, nước không hai vua",
    "Rừng nào cọp nấy",
    "Ráng mỡ gà,có nhà thì giữ",
    "Sinh nghề tử nghiệp",
    "Sinh lão bệnh tử",
    "Sinh li tử biệt",
    "Sông có khúc, người có lúc",
    "Sóng Trường Giang, sóng sau đập sóng trước",
    "Sông sâu còn có kẻ dò, đố ai lấy thước mà đo lòng người",
    "Sai một li đi một dặm",
    "Sự thật mất lòng",
    "Sông sâu sóng cả chớ ngã tay chèo",
    "Sông cạn đá mòn",
    "Sóng trước đổ đâu, sóng sau đổ đó.",
    "Sinh cơ lập nghiệp",
    "Ta về ta tắm ao ta, dù trong dù đục ao nhà vẫn hơn.",
    "Tấc đất tấc vàng",
    "Tai vách mạch rừng.",
    "Tẩm ngẩm tầm ngầm mà đấm chết voi",
    "Tâm cuồng, trí loạn.",
    "Tay làm hàm nhai, tay quai miệng trễ.",
    "Té nước theo mưa.",
    "Tình sâu, nghĩa nặng.",
    "Tình thương quán cũng là nhà, lều tranh có nghĩa hơn tòa ngói cao.",
    "Tiên học lễ hậu học văn",
    "Tiền vào nhà khó như gió vào nhà trống.",
    "Tiền vào quan như than vào lò",
    "Tiền nào của đó",
    "Tốt gỗ hơn tốt nước sơn, xấu người đẹp nết con hơn đẹp người",
    "Tôm đi chạng vạng, cá đi rạng đông.",
    "Tốt danh hơn lành áo.",
    "Tháng bảy kiến bò, chỉ lo lại lụt",
    "Tham giàu phụ khó. tham sang phụ phần",
    "Tham giàu phụ ngải",
    "Tham phú phụ bần",
    "Thất bại là mẹ thành công",
    "Thật thà là cha dại.",
    "Thật thà ăn cháo, láo nháo ăn cơm",
    "Thắng làm vua thua làm giặc",
    "Thuận vợ thuận chồng, tát biển Đông cũng cạn.",
    "Thương cho roi cho vọt, ghét cho ngọt cho bùi",
    "Thương nhau mấy núi cũng trèo, mấy sông cũng lội mấy đèo cũng qua",
    "Thua thầy một vạn không bằng kém bạn một li",
    "Thân sâu hồn bướm",
    "Thừa nước đục thả câu",
    "Thả hổ về rừng",
    "Thua keo này bày keo khác",
    "Thuyền to sóng cả.",
    "Thầy bói xem voi",
    "Tháng hai trồng cà, tháng ba trồng đỗ.",
    "Thùng rỗng kêu to.",
    "Tránh vỏ dưa gặp vỏ dừa",
    "Trăm đường tránh không khỏi số.",
    "Trăm hay không bằng tay quen.",
    "Trăm nghe không bằng một thấy.",
    "Trăm năm bia đá cũng mòn, nghìn năm bia miệng vẫn còn trơ trơ.",
    "Trăng quầng thì hạn, trăng tán thì mưa.",
    "Trăm người bán vạn người mua.",
    "Trâu buộc ghét trâu ăn.",
    "Trâu cột ghét trâu ăn.",
    "Trâu già thích gặm cỏ non.",
    "Tre già măng mọc.",
    "Tránh voi chẳng xấu mặt nào.",
    "Trong cái khó lại ló cái khôn.",
    "Trống làng nào làng ấy đánh.",
    "Uống nước nhớ nguồn",
    "Ước gì được nấy",
    "Ướt như chuột lột",
    "Uốn cây từ thuở còn non. Dạy con từ thuở con còn ngây thơ.",
    "Vỏ quýt dày có móng tay nhọn",
    "Vắng chủ nhà gà vọc niêu tôm",
    "Việc nhà thì ngán, việc làng thì siêng.",
    "Việc nước trước việc nhà.",
    "Vụng chèo khéo trống",
    "Việc nhà thì nhác việc chú bác thì siêng",
    "Văn hay chữ tốt",
    "Việc người thì sáng, việc mình thì quáng",
    "Xa sông, cách núi.",
    "Xấu hay làm tốt, dốt hay nói chữ",
    "Xôi hỏng bỏng không",
    "Xa thơm gần thối",
    "Xa thương, gần thường",
    "Xem bói ra ma, quét nhà ra rác",
    "Xởi lởi trời cho, so đo trời lấy lại",
    "Xa mặt cách lòng",
    "Yêu nhau lắm, cắn nhau đau",
    "Yêu nhau cau sáu bổ ba, ghét nhau cau sáu bổ ra làm mười",
    "Yêu trẻ, trẻ đến nhà; kính già, già để tuổi cho.",
    "Yêu nhau yêu cả đường đi, ghét nhau ghét cả tông chi họ hàng",
    "Yêu nhau vạn sự chẳng nề, dẫu trăm chỗ lệch cũng kê cho bằng",
    "Yêu nhau xa cũng nên gần, ghét nhau cách một bàn chân cũng lìa",
]


def proverb_of_day(d: date = None) -> str:
    """Tra ve 1 cau tuc ngu ngau nhien nhung on dinh cho ngay d (moi ngay 1 cau khac nhau)."""
    d = d or date.today()
    rng = random.Random(d.toordinal())
    return rng.choice(PROVERBS)
