"""
Kho cau quote hay - nguoi dung tu tong hop va cung cap (co ghi tac gia).
Moi ngay bot chon ngau nhien 1 cau (seed theo ngay, on dinh trong ngay).
"""
import random
from datetime import date

# Moi phan tu: (cau, tac_gia)
QUOTES = [
    ("Đàn ông kết hôn vì họ mệt mỏi. Phụ nữ kết hôn vì họ tò mò. Cả hai đều thất vọng.", "Oscar Wilde"),
    ("Người lạc quan thấy cái bánh tròn, kẻ bi quan thấy cái lỗ.", "Oscar Wilde"),
    ("Đừng bao giờ yêu thương ai nếu người đó đối xử với bạn như thể bạn là một người tầm thường.", "Oscar Wilde"),
    ("Yêu thương bản thân, đó là khởi đầu của một mối tình suốt đời.", "Oscar Wilde"),
    ("Hôn nhân là sự chiến thắng của trí tưởng tượng trước trí tuệ. Cuộc hôn nhân thứ hai là sự chiến thắng của hy vọng trước kinh nghiệm.", "Oscar Wilde"),
    ("Không phải ai cũng tốt đẹp, nhưng luôn có điều gì đó tốt đẹp trong bất cứ ai. Đừng bao giờ vội vã phán xét người khác bởi vì vị thánh nào cũng có một quá khứ và kẻ tội đồ nào cũng có một tương lai.", "Oscar Wilde"),
    ("Tôi đã thấy khi đàn ông yêu phụ nữ. Họ trao đi chỉ một phần nhỏ của cuộc đời mình. Nhưng khi phụ nữ yêu, họ cho đi mọi thứ.", "Oscar Wilde"),
    ("Bất cứ ai chỉ sống với những gì mình có đều phải khổ vì sự thiếu tưởng tượng.", "Oscar Wilde"),
    ("Hãy là chính mình; tất cả ai khác đều có người làm rồi.", "Oscar Wilde"),
    ("Phụ nữ được tạo ra để ta yêu thương, chứ không phải để ta hiểu.", "Oscar Wilde"),
    ("Cái chết hẳn phải rất đẹp đẽ. Nằm trong đất nâu mềm, cỏ đung đưa trên đầu, lắng nghe sự yên lặng. Không có quá khứ và không có tương lai. Quên đi thời gian, tha thứ cuộc sống, hoàn toàn yên bình.", "Oscar Wilde"),
    ("Người duy nhất bạn cần trong đời là người cho bạn thấy anh ta cũng cần bạn trong đời.", "Oscar Wilde"),
    ("Có tự do, sách, hoa và mặt trăng, ai có thể không hạnh phúc kia chứ?", "Oscar Wilde"),
    ("Nếu hay thì kết thúc hạnh phúc, nếu không hay thì kết thúc bất hạnh. Tiểu thuyết nghĩa là như thế.", "Oscar Wilde"),
    ("Ai cũng có thể cảm thông với sự đau khổ của bạn mình, nhưng phải có được một bản tính rất tốt đẹp để có thể vui cùng thành công của bạn.", "Oscar Wilde"),
    ("Thật vớ vẩn khi chia người đời ra làm người tốt và người xấu. Người đời hoặc lôi cuốn, hoặc chán ngắt.", "Oscar Wilde"),
    ("Sự ích kỷ không phải là sống như cách mình muốn, mà là đòi hỏi người khác phải sống như cách mình muốn.", "Oscar Wilde"),
    ("Giữa đàn ông và phụ nữ không thể có tình bạn. Có thể có đam mê, có thù địch, có sự tôn sùng, có tình yêu, nhưng không có tình bạn.", "Oscar Wilde"),
    ("Đàn ông có thể có hạnh phúc với bất cứ người phụ nữ nào, miễn là không yêu nàng.", "Oscar Wilde"),
    ("Tình bạn bi kịch hơn tình yêu. Nó tồn tại lâu hơn.", "Oscar Wilde"),
    ("Chúng ta đều ở trong rãnh nước, nhưng có vài người biết ngước lên trời sao.", "Oscar Wilde"),
    ("Khi tôi còn trẻ, tôi nghĩ tiền bạc là thứ quan trọng nhất trong đời; giờ khi tôi già rồi, tôi biết đúng là như thế.", "Oscar Wilde"),
    ("Tôi chọn bạn bè vì vẻ ngoài đẹp đẽ, người quen biết vì tính cách tốt đẹp, và kẻ thù vì trí tuệ thông minh.", "Oscar Wilde"),
    ("Nếu em không lâu quá, anh sẽ chờ em ở đây suốt cả cuộc đời.", "Oscar Wilde"),
    ("Con người ít là bản thân mình nhất khi nói với tư cách của bản thân. Hãy cho anh ta một cái mặt nạ, và anh ta sẽ nói với bạn sự thật.", "Oscar Wilde"),
    ("Người lạc quan sẽ bảo bạn cái cốc đầy một nửa; kẻ bi quan sẽ bảo bạn cái cốc vơi một nửa; và anh kỹ sư sẽ bảo bạn cái cốc to hơn gấp đôi kích cỡ cần thiết của nó.", "Oscar Wilde"),
    ("Khi đàn ông từng yêu một người phụ nữ, anh ta sẽ làm mọi thứ vì nàng, trừ việc tiếp tục yêu nàng.", "Oscar Wilde"),
    ("Cái đẹp là thứ duy nhất mà thời gian không thể làm tổn hại. Triết lý sẽ rơi rụng như cát, tín ngưỡng sẽ không ngừng bị thay thế, nhưng cái đẹp luôn là niềm vui suốt vĩnh hằng.", "Oscar Wilde"),
    ("Kẻ bi quan là kẻ phàn nàn về tiếng ồn khi cơ hội gõ cửa.", "Oscar Wilde"),
    ("Sống là điều hiếm thấy nhất trên thế gian. Phần lớn người đời chỉ tồn tại mà thôi.", "Oscar Wilde"),
    ("Bí ẩn cuối cùng là chính bản thân ta. Khi ta đã tính toán được khối lượng của mặt trời, và đo được khoảng cách tới mặt trăng, và lập bản đồ sao cả bảy thiên đường, vẫn còn chính bản thân ta. Ai có thể tính toán được quỹ đạo của chính tâm hồn mình?", "Oscar Wilde"),
    ("Thứ mà chúng ta thấy là thử thách đầy cay đắng thường lại là phúc lành khoác cải trang.", "Oscar Wilde"),
    ("Hãy luôn tha thứ cho kẻ thù; không gì làm họ bực mình hơn thế.", "Oscar Wilde"),
    ("Ký ức... đó là cuốn nhật ký tất cả chúng ta đều mang theo bên mình.", "Oscar Wilde"),
    ("Sự thỏa mãn đích thực không nằm ở việc có được mọi thứ, mà nằm ở việc hài lòng với mọi thứ bạn có.", "Oscar Wilde"),
    ("Cuộc đời chẳng bao giờ công bằng, và có lẽ với hầu hết chúng ta, thật may mắn vì là như thế.", "Oscar Wilde"),
    ("Làm sao phụ nữ lại có thể mong chờ hạnh phúc với người đàn ông luôn đối xử với nàng như thể nàng chỉ là một người rất đỗi bình thường?", "Oscar Wilde"),
    ("Đạo đức chỉ đơn giản là thái độ mà chúng ta có đối với những người mà ta ghét.", "Oscar Wilde"),
    ("Tiếng cười không hề là điểm khởi đầu xấu cho tình bạn, và hoàn toàn là điểm kết thúc tốt nhất của tình bạn.", "Oscar Wilde"),
    ("Đàn ông luôn muốn là tình yêu đầu tiên của phụ nữ - phụ nữ lại muốn là mối tình cuối cùng của đàn ông.", "Oscar Wilde"),
    ("Kinh nghiệm là thứ bạn không thể có mà không trả giá.", "Oscar Wilde"),
    ("Tôi là người duy nhất trên thế gian mà tôi muốn hiểu rõ sâu sắc.", "Oscar Wilde"),
    ("Nghệ thuật là gì? - Là căn bệnh. Tình yêu là gì? - Là ảo ảnh. Tôn giáo là gì? - Là thứ thay thế phong cách cho Đức tin. Anh đúng là kẻ ưa hoài nghi. - Không bao giờ! Hoài nghi là điểm bắt đầu của Tin tưởng. Vậy anh là gì? - Định nghĩa là giới hạn.", "Oscar Wilde"),
    ("Kẻ buồn chán là kẻ lấy đi sự cô độc của bạn mà lại không cho bạn sự bầu bạn.", "Oscar Wilde"),
    ("Định nghĩa có nghĩa là giới hạn.", "Oscar Wilde"),
    ("Nếu bạn không thể tìm niềm vui trong việc đọc đi đọc lại một cuốn sách, đọc nó hoàn toàn chẳng có ích gì.", "Oscar Wilde"),
    ("Một chút chân thành là điều nguy hiểm, và nhiều chân thành tuyệt đối là nguy hiểm chết người.", "Oscar Wilde"),
    ("Bạn không yêu người khác vì vẻ ngoài hay quần áo hay xe hơi sang trọng của họ, mà bởi họ hát bài ca mà chỉ bạn có thể nghe thấy.", "Oscar Wilde"),
    ("Đừng dùng những lời lẽ to tát. Chúng chẳng có bao nhiêu ý nghĩa.", "Oscar Wilde"),
    ("Trái tim được tạo ra để tan vỡ.", "Oscar Wilde"),
    ("Một thứ không nhất thiết là đúng chỉ bởi có người chịu chết vì nó.", "Oscar Wilde"),
    ("Điều mà bạn đọc khi bạn không buộc phải đọc sẽ quyết định bạn sẽ là người như thế nào trong hoàn cảnh bạn không thể chi phối.", "Oscar Wilde"),
    ("Một nụ hôn có thể làm hỏng cả cuộc đời của một người.", "Oscar Wilde"),
    ("Tôi thông minh đến nỗi đôi lúc tôi chẳng hiểu nổi mình đang nói cái gì.", "Oscar Wilde"),
    ("Có thu nhập bất biến thì tốt hơn là chỉ được yêu quý.", "Oscar Wilde"),
    ("Con người luôn luôn nên trong trạng thái đang yêu. Đó là lý do người ta chẳng bao giờ nên kết hôn.", "Oscar Wilde"),
    ("Mèo xuất hiện trên thế gian để nhắc ta nhớ rằng không phải điều gì cũng có mục đích.", "Oscar Wilde"),
    ("Tôi thích những người đàn ông có tương lai và những người phụ nữ có quá khứ.", "Oscar Wilde"),
    ("Người không nghĩ cho bản thân hoàn toàn chẳng hề suy nghĩ.", "Oscar Wilde"),
    ("Gương mặt của đàn ông là cuốn tiểu sử của anh ta. Gương mặt của phụ nữ là tác phẩm giả tưởng của cô ta.", "Oscar Wilde"),
    ("Người già tin vào mọi thứ, người trung niên nghi ngờ mọi thứ, người trẻ tuổi biết mọi thứ.", "Oscar Wilde"),
    ("Bất cứ khi nào có người làm chuyện hoàn toàn cực kỳ ngu xuẩn, nó thường luôn là vì những động cơ cao cả nhất.", "Oscar Wilde"),
    ("Hầu hết con người sống là người khác. Ý nghĩ của họ là quan điểm của ai đó, cuộc sống của họ là sự bắt chước, đam mê của họ là lời trích dẫn.", "Oscar Wilde"),
    ("Có điều hay ho về hôn nhân là nó khiến cuộc sống dối lừa trở nên tuyệt đối cần thiết với cả hai bên.", "Oscar Wilde"),
    ("Nghệ thuật là hình thức mãnh liệt nhất của chủ nghĩa cá nhân mà thế gian từng chứng kiến.", "Oscar Wilde"),
    ("Xã hội thường tha thứ cho kẻ phạm tội; nó chẳng bao giờ tha thứ cho người mơ mộng.", "Oscar Wilde"),
    ("Công chúng có sự tò mò không thể thỏa mãn muốn biết mọi chuyện, trừ chuyện đáng biết.", "Oscar Wilde"),
    ("Bạn thích tất cả mọi người; nói thế cũng là nói, bạn thờ ơ với tất cả mọi người.", "Oscar Wilde"),
    ("Có những thứ đáng giá hơn bởi chúng không tồn tại dài lâu.", "Oscar Wilde"),
    ("Người ta có thể thất bại nhiều lần, nhưng người ta chỉ trở thành thất bại khi bắt đầu đổ lỗi cho người khác.", "Oscar Wilde"),
    ("Cuộc sống chân thực của một người thường là cuộc sống mà người đó không sống.", "Oscar Wilde"),
    ("Sự nhất quán là nơi trú ẩn cuối cùng của người không có trí tưởng tượng.", "Oscar Wilde"),
    ("Người hoài nghi là gì? Là người biết cái giá của mọi thứ, và chẳng biết giá trị của thứ gì.", "Oscar Wilde"),
    ("Con người hào hoa phong nhã là người không bao giờ làm tổn thương người khác mà không cố ý.", "Oscar Wilde"),
    ("Hãy sống! Hãy sống cuộc đời tuyệt vời náu mình trong bạn! Đừng để bạn bỏ lỡ điều gì. Hãy luôn tìm kiếm những cảm xúc mới. Đừng sợ gì cả!", "Oscar Wilde"),
    ("Đừng cảm thấy nản lòng nếu con cái không nghe theo lời khuyên của bạn. Hàng năm sau, chúng sẽ cho con cái chúng chính lời khuyên ấy.", "Oscar Wilde"),
    ("Một ý tưởng mà không nguy hiểm thì chẳng đáng được gọi là ý tưởng.", "Oscar Wilde"),
    ("Tôi luôn luôn có quan điểm sự chăm chỉ chỉ đơn thuần là nơi ẩn náu của những người chẳng có việc gì để làm.", "Oscar Wilde"),
    ("Cuộc sống không phức tạp. Chúng ta phức tạp. Cuộc sống giản đơn, và giản đơn là điều đúng đắn.", "Oscar Wilde"),
    ("Hãy luôn mượn tiền từ kẻ bi quan. Anh ta sẽ không hy vọng được trả lại.", "Oscar Wilde"),
    ("Tôi chẳng bao giờ trì hoãn đến ngày mai việc tôi có thể làm - vào ngày kia.", "Oscar Wilde"),
    ("Nhân loại coi mình quá nghiêm túc. Đó là tội lỗi đầu tiên của thế giới. Nếu gã người tiền sử biết cách cười, Lịch sử hẳn đã khác đi.", "Oscar Wilde"),
    ("Mỗi bức chân dung được vẽ với tình cảm là bức chân dung của người họa sĩ, không phải của người làm mẫu.", "Oscar Wilde"),
    ("Có nhiều thứ mà ta hẳn sẽ vứt đi nếu ta không sợ người khác có thể sẽ nhặt được chúng.", "Oscar Wilde"),
    ("Hoàn toàn có thể đạt được thứ bạn nghĩ mình muốn và vẫn khốn khổ. Cũng có thể không bao giờ đạt được nó, nhưng tận hưởng sâu sắc quá trình nỗ lực phấn đấu. Trên thế gian này chỉ có hai bi kịch: một là không đạt được điều mình muốn, và bi kịch còn lại là đạt được nó.", "Oscar Wilde"),
    ("Tôi nghĩ khi tạo ra con người, Chúa đã đánh giá hơi quá cao khả năng của mình.", "Oscar Wilde"),
    ("Luôn luôn có điều gì đó nực cười về cảm xúc của những người mà ta không còn yêu thương nữa.", "Oscar Wilde"),
    ("Hãy giữ yêu thương trong trái tim. Cuộc đời không có tình yêu thương giống như khu vườn không nắng nơi mà hoa cỏ đều đã chết.", "Oscar Wilde"),
    ("Người mơ mộng là người chỉ có thể tìm được đường nhờ ánh trăng, và sự trừng phạt của anh ta là anh ta thấy bình minh trước phần còn lại của thế giới.", "Oscar Wilde"),
    ("Phải có rất nhiều can đảm để nhìn thế gian trong tất cả ánh hào quang vấy bẩn của nó, và vẫn yêu nó.", "Oscar Wilde"),
    ("Cẩn thận khi lựa chọn kẻ thù không bao giờ là quá thừa thãi.", "Oscar Wilde"),
    ("Bí ẩn của tình yêu lớn lao hơn bí ẩn của cái chết.", "Oscar Wilde"),
    ("Điều duy nhất có thể làm với lời khuyên tốt là trao nó đi. Nó chẳng bao giờ có ích với chính mình.", "Oscar Wilde"),
    ("Có lợi ích xa xỉ trong việc tự trách cứ bản thân. Khi ta quy lỗi cho bản thân mình, ta cảm thấy không ai có quyền đổ lỗi cho ta nữa.", "Oscar Wilde"),
    ("Bạn chẳng bao giờ có thể ăn mặc quá mức hay có học vấn quá mức.", "Oscar Wilde"),
    ("Hai người nhìn ra khỏi cửa sổ. Người thấy bùn lầy, người thấy sao trời.", "Oscar Wilde"),
    ("Sự sáng suốt đến cùng với tuổi tác, nhưng đôi khi tuổi tác chỉ đến một mình.", "Oscar Wilde"),
    ("Nếu bạn muốn nói với người khác sự thật, hãy khiến họ cười, nếu không họ sẽ giết bạn.", "Oscar Wilde"),
    ("Con người xuất sắc; anh ta không có kẻ thù; và cũng chẳng được bạn bè nào ưa thích.", "Oscar Wilde"),
    ("Tôi không muốn lên thiên đường. Bạn bè tôi chẳng ai ở đó.", "Oscar Wilde"),
    ("Không gì có thể chữa trị tâm hồn ngoài tri giác, cũng như không gì có thể chữa trị tri giác ngoài tâm hồn.", "Oscar Wilde"),
    ("Người ta hứa rằng giấc mơ có thể trở thành hiện thực - nhưng lại quên nhắc đến việc ác mộng cũng là giấc mơ.", "Oscar Wilde"),
    ("Luôn luôn! Đó là một từ đáng sợ. Nó khiến tôi run lên khi nghe thấy nó. Phụ nữ thích dùng nó. Họ làm hỏng mọi cuộc tình lãng mạn khi cố gắng biến cuộc tình thành vĩnh cửu. Nó cũng là một từ vô nghĩa nữa. Sự khác biệt duy nhất giữa đoạn tình chóng vánh và đam mê suốt đời là đoạn tình chóng vánh tồn tại dài hơn chút xíu.", "Oscar Wilde"),
    ("Điều tốt đẹp mà ta có được từ nghệ thuật không phải là điều ta học được từ nó; mà là con người ta trở thành thông qua nó.", "Oscar Wilde"),
    ("Hối tiếc trải nghiệm của bản thân là ngăn chặn sự phát triển của chính mình. Phủ nhận trải nghiệm của bản thân là thì thầm lời nói dối trên môi cuộc đời của chính mình. Điều đó không gì khác chính là phủ nhận tâm hồn mình.", "Oscar Wilde"),
    ("Lợi thế của cảm xúc là chúng dẫn ta đi lạc đường.", "Oscar Wilde"),
    ("Phụ nữ yêu chúng ta vì những khuyết điểm của ta. Nếu ta có đủ khuyết điểm, họ sẽ tha thứ ta mọi chuyện, thậm chí cả trí tuệ phi phàm của ta.", "Oscar Wilde"),
    ("Xã hội chỉ tồn tại như là một khái niệm của tinh thần; trong thế giới thực, chỉ có các cá nhân.", "Oscar Wilde"),
    ("Nếu một thứ đáng làm, nó đáng làm tốt. Nếu một thứ đáng có, nó đáng để chờ đợi. Nếu một thứ đáng đạt được, nó đáng để tranh đấu. Nếu một thứ đáng trải nghiệm, nó đáng để ta dành thời gian.", "Oscar Wilde"),
    ("Mỗi chúng ta đều là ác quỷ của chình mình, và chúng ta biến thế gian này thành địa ngục của mình.", "Oscar Wilde"),
    ("Cuộc lãng mạn không bao giờ nên bắt đầu với tình cảm. Nó nên bắt đầu với khoa học và kết thúc với một thỏa thuận.", "Oscar Wilde"),
    ("Kẻ bi quan: Người khi phải lựa chọn giữa hai cái ác, sẽ chọn cả hai.", "Oscar Wilde"),
    ("Trên thế gian chỉ có một điều duy nhất tồi tệ hơn việc bị người ta đàm luận, đó là không được ai nhắc đến.", "Oscar Wilde"),
    ("Thi sĩ có thể sống sót qua mọi thứ, trừ lỗi in ấn.", "Oscar Wilde"),
    ("Hận thù mù quáng, và tình yêu cũng vậy.", "Oscar Wilde"),
    ("Cách tốt nhất để yêu thích công việc của mình là hãy tưởng tượng mình không có việc.", "Oscar Wilde"),
    ("Cốt lõi cơ bản nhất của lãng mạn là sự không chắc chắn.", "Oscar Wilde"),
    ("Có những khoảng khắc mà người ta phải chọn giữa việc sống cuộc đời của bản thân một cách hoàn toàn và trọn vẹn - hay kéo lê thê sự tồn tại giả tạo, nông cạn và đê hèn mà thế giới đòi hỏi trong thói đạo đức giả của nó.", "Oscar Wilde"),
    ("Khi người phụ nữ tái hôn, đó là bởi nàng căm ghét ông chồng đầu tiên. Khi người đàn ông tái hôn, đó là bởi anh ta mê mẩn người vợ đầu tiên. Phụ nữ thử xem vận may của mình; đàn ông mạo hiểm vận may của mình.", "Oscar Wilde"),
    ("Trong mắt của bất cứ ai đã đọc về lịch sử, sự bất tuân là một đức tính gốc gác của con người. Chính qua sự bất tuân mà có được sự tiến bộ, qua sự bất tuân và qua phản kháng.", "Oscar Wilde"),
    ("Mọi thứ đều có mức độ, ngay cả mức độ.", "Oscar Wilde"),
    ("Nghệ thuật là thứ duy nhất nghiêm túc trên thế gian. Và người nghệ sĩ là người duy nhất chẳng bao giờ nghiêm túc.", "Oscar Wilde"),
    ("Thế giới trở nên hoài nghi với bất cứ thứ gì có vẻ giống như một cuộc sống hôn nhân hạnh phúc.", "Oscar Wilde"),
    ("Tôi chưa bao giờ trao sự tôn sùng cho bất cứ ai trừ chính mình.", "Oscar Wilde"),
    ("Không người nghệ sĩ vĩ đại nào lại thấy mọi thứ như bản chất của nó. Nếu anh ta thấy như vậy, anh ta sẽ không còn là nghệ sĩ.", "Oscar Wilde"),
    ("Mục đích của cuộc đời là phát triển bản thân. Nhận ra thấu suốt bản tính của mình - đó là lý do tại sao mỗi chúng ta lại ở đây.", "Oscar Wilde"),
    ("Tôi không muốn bị dòng cảm xúc cuốn trôi. Tôi muốn sử dụng chúng, tận hưởng chúng, và chi phối chúng.", "Oscar Wilde"),
    ("Thế gian chia làm hai loại người, người tin vào điều không thể tin, và người làm điều không chắc sẽ thành.", "Oscar Wilde"),
    ("Người bạn tốt sẽ chỉ luôn đâm bạn từ phía trước.", "Oscar Wilde"),
    ("Kinh nghiệm chỉ đơn giản là cách mà ta gọi sai lầm của mình.", "Oscar Wilde"),
    ("Thành công là một môn khoa học; nếu bạn có đủ điều kiện, bạn sẽ có kết quả.", "Oscar Wilde"),
    ("Có thể tôi không đồng ý với anh, nhưng tôi sẽ bảo vệ tới chết quyền tự biến mình thành trò cười của anh.", "Oscar Wilde"),
    ("Con người là loài động vật lý trí luôn luôn đánh mất sự bình tĩnh khi buộc phải hành động theo mệnh lệnh của lý trí.", "Oscar Wilde"),
    ("Thời trang là một dạng xấu không thể chịu nổi đến mức cứ sáu tháng ta lại phải thay đổi một lần.", "Oscar Wilde"),
    ("Đừng bao giờ hối tiếc mình đã rơi,\nHỡi Icarus không biết sợ,\nBởi bi kịch lớn lao nhất,\nLà chẳng bao giờ cảm nhận sự thiêu đốt.", "Oscar Wilde"),
    ("Ngôn từ! Chỉ là ngôn từ mà thôi! Chúng mới kinh khủng làm sao! Rõ ràng, sống động, và tàn nhẫn làm sao! Người ta không thể trốn khỏi chúng. Và vậy mà trong chúng có phép màu tinh tế làm sao! Chúng dường như có thể trao hình hài cho những thứ vô hình dáng, và tự thân có âm nhạc cũng ngọt ngào như tiếng đàn viôn hay tiếng sáo. Chỉ là ngôn từ mà thôi! Còn có thứ gì thực hơn ngôn từ sao?", "Oscar Wilde"),
    ("Thế giới là sân khấu và vở diễn được diễn tồi.", "Oscar Wilde"),
    ("Thế giới là con hàu của tôi nhưng tôi đã dùng nhầm dĩa.", "Oscar Wilde"),
    ("Người ta có thể đánh giá một người qua ảnh hưởng mà anh ta tác động đến bạn bè mình.", "Oscar Wilde"),
    ("Chỉ có hai loại người thực sự lôi cuốn - người tuyệt đối biết mọi thứ và người tuyệt đối chẳng biết thứ gì.", "Oscar Wilde"),
    ("Tôn giáo giống như một người mù đi tìm con mèo đen không tồn tại trong căn phòng tối, và tìm thấy nó.", "Oscar Wilde"),
    ("Không ai đủ giàu để mua lại quá khứ của mình.", "Oscar Wilde"),
    ("Sự thật hiếm khi thuần túy và chẳng bao giờ đơn giản.", "Oscar Wilde"),
    ("Tai tiếng chỉ là lời đồn đại trở nên nhàm chán bởi đạo đức.", "Oscar Wilde"),
    ("Mục đích của cuộc đời là phát triển bản thân. Nhận ra trọn vẹn bản chất của mình — đó là lý do mỗi chúng ta có mặt trên đời.", "Oscar Wilde"),
    ("Chỉ những người nông cạn mới hiểu rõ chính mình.", "Oscar Wilde"),
    ("Những hành động thấp hèn giống như cỏ độc nở rộ trong không khí nhà tù; chỉ những điều tốt đẹp trong con người là lụi tàn và héo úa nơi đó.", "Oscar Wilde"),
    ("Ngày nay, chúng ta thực sự có mọi thứ chung với nước Mỹ, ngoại trừ tất nhiên là ngôn ngữ.", "Oscar Wilde"),
    ("Vậy sự khác biệt giữa văn học và báo chí là gì? Báo chí thì không thể đọc nổi, còn văn học thì chẳng ai đọc. Chỉ vậy thôi.", "Oscar Wilde"),
    ("Chỉ có người bán đấu giá mới có thể ngưỡng mộ một cách bình đẳng và vô tư tất cả các trường phái nghệ thuật.", "Oscar Wilde"),
    ("Công chúng thật đáng kinh ngạc ở sự khoan dung. Họ tha thứ cho tất cả mọi thứ, ngoại trừ thiên tài.", "Oscar Wilde"),
    ("Một chút chân thành là điều nguy hiểm, còn quá nhiều chân thành thì hoàn toàn chí mạng.", "Oscar Wilde"),
    ("Người ta có thể định nghĩa con người là một loài động vật có lý trí, nhưng luôn mất bình tĩnh khi được yêu cầu hành động theo lý trí.", "Oscar Wilde"),
    ("Sự thật hiếm khi thuần khiết và chẳng bao giờ đơn giản.", "Oscar Wilde"),
    ("Mất một người cha hoặc mẹ có thể được xem là bất hạnh; mất cả hai thì trông giống như sự bất cẩn.", "Oscar Wilde"),
    ("Tuổi ba mươi lăm là một độ tuổi vô cùng hấp dẫn. Xã hội London đầy những phụ nữ thuộc dòng dõi cao quý, những người tự nguyện ở tuổi ba mươi lăm suốt nhiều năm.", "Oscar Wilde"),
    ("Có một khoản thu nhập ổn định vẫn tốt hơn là trở thành người quyến rũ.", "Oscar Wilde"),
    ("Không ai có thể quá cẩn thận trong việc lựa chọn kẻ thù của mình.", "Oscar Wilde"),
    ("Trẻ con bắt đầu bằng việc yêu thương cha mẹ; khi lớn lên, chúng phán xét cha mẹ; đôi khi chúng tha thứ cho họ.", "Oscar Wilde"),
    ("Tôi yêu những thú vui giản dị. Chúng là nơi trú ẩn cuối cùng của những người phức tạp.", "Oscar Wilde"),
    ("Tôi có thể tin bất cứ điều gì, miễn là điều đó hoàn toàn không thể tin được.", "Oscar Wilde"),
    ("Tôi chọn bạn bè vì vẻ ngoài đẹp đẽ, người quen vì tính cách tốt, và kẻ thù vì trí tuệ sắc bén. Không ai có thể quá cẩn thận trong việc lựa chọn kẻ thù.", "Oscar Wilde"),
    ("Tôi thích con người hơn những nguyên tắc, và tôi thích những người không có nguyên tắc hơn bất cứ thứ gì khác trên đời.", "Oscar Wilde"),
    ("Tôi yêu diễn xuất. Nó chân thực hơn cuộc sống rất nhiều.", "Oscar Wilde"),
    ("Ngày nay, phần lớn con người chết vì một thứ gọi là lẽ thường ngày càng len lỏi, và đến khi quá muộn họ mới nhận ra rằng điều duy nhất ta không bao giờ hối tiếc chính là những sai lầm của mình.", "Oscar Wilde"),
    ("Ta luôn có thể tử tế với những người mà ta chẳng hề quan tâm.", "Oscar Wilde"),
    ("Có lẽ nước Mỹ chưa bao giờ thực sự được khám phá. Chính tôi sẽ nói rằng nó chỉ đơn thuần được phát hiện.", "Oscar Wilde"),
    ("Ưu điểm của cảm xúc là chúng dẫn ta đi lạc đường, còn ưu điểm của khoa học là nó không bị cảm xúc chi phối.", "Oscar Wilde"),
    ("Nền tảng của sự lạc quan chính là nỗi kinh hoàng thuần túy.", "Oscar Wilde"),
    ("Cách duy nhất để thoát khỏi một cám dỗ là chiều theo nó.", "Oscar Wilde"),
    ("Cách duy nhất để thoát khỏi một cám dỗ là chiều theo nó. Hãy chống lại nó, và tâm hồn bạn sẽ trở nên bệnh hoạn vì khao khát những điều mà chính nó đã cấm đoán.", "Oscar Wilde"),
    ("Có rất nhiều thứ mà chúng ta sẽ vứt bỏ nếu không sợ rằng người khác có thể nhặt chúng lên.", "Oscar Wilde"),
    ("Có một sự xa xỉ trong việc tự trách mình. Khi tự đổ lỗi cho bản thân, ta cảm thấy không ai khác có quyền trách cứ ta. Chính lời thú tội, chứ không phải vị linh mục, mang đến cho ta sự tha thứ.", "Oscar Wilde"),
    ("Nếu muốn lấy lại tuổi trẻ, tôi sẽ làm bất cứ điều gì trên đời, ngoại trừ tập thể dục, dậy sớm hoặc sống một cách đứng đắn.", "Oscar Wilde"),
    ("Khi một người phụ nữ tái hôn, đó là vì nàng căm ghét người chồng đầu tiên. Khi một người đàn ông tái hôn, đó là vì anh ta từng yêu say đắm người vợ đầu tiên. Phụ nữ thử vận may; đàn ông đánh cược vận may của mình.", "Oscar Wilde"),
    ("Bất cứ khi nào một người đàn ông làm một việc ngu ngốc đến mức hoàn toàn, thì đó luôn là vì những động cơ cao cả nhất.", "Oscar Wilde"),
    ("Phụ nữ yêu chúng ta vì những khuyết điểm của chúng ta. Nếu chúng ta có đủ khuyết điểm, họ sẽ tha thứ cho chúng ta mọi thứ, kể cả trí tuệ của chúng ta.", "Oscar Wilde"),
    ("Không có cuốn sách nào là đạo đức hay vô đạo đức. Sách được viết hay hoặc viết dở.", "Oscar Wilde"),
    ("Ai cũng có thể cảm thông với nỗi đau khổ của một người bạn, nhưng phải có một tâm hồn rất cao đẹp mới có thể cảm thông với thành công của bạn mình.", "Oscar Wilde"),
    ("Tôi cho rằng cuối cùng mình sẽ phải chết vượt quá khả năng tài chính của bản thân.", "Oscar Wilde"),
    ("Một hành động tử tế dù nhỏ bé nhất cũng đáng giá hơn ý định cao cả nhất.", "Oscar Wilde"),
    ("Tôi xem sân khấu là loại hình nghệ thuật vĩ đại nhất, là cách trực tiếp nhất để một con người có thể chia sẻ với người khác cảm nhận về việc được làm một con người.", "Oscar Wilde"),
    ("Bí ẩn thực sự của thế giới là cái hữu hình, chứ không phải cái vô hình.", "Oscar Wilde"),
]


def quote_of_day(d: date = None):
    """Tra ve (cau, tac_gia) ngau nhien nhung on dinh cho ngay d."""
    d = d or date.today()
    rng = random.Random(d.toordinal() + 99991)  # lech seed de khac voi proverbs
    return rng.choice(QUOTES)
